# Customizes the menu bar of the G4UIQt / G4UIXm sessions.
# It has no effect with a terminal session.

# File menu
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu
/gui/addMenu run Run
/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run "beamOn 100" "/run/beamOn 100"
/gui/addButton run "beamOn 1000" "/run/beamOn 1000"
#
# Viewer menu
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# Limit the output flow in the "dump" widget
/run/printProgress 100
