# GENERATED by tools/generate_kernels.py -- do not edit.
# sympy version: 1.14.0
# formula ids: F-KERN-1, F-KERN-2, F-KERN-4
# command: python tools/generate_kernels.py
# ruff: noqa: E501, F401

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray
from scipy.special import erf


def gaussian_bin_probability(e_lo, e_hi, c, sigma):
    """F-KERN-1: exact Gaussian bin integral (no taper)."""
    e_lo = np.asarray(e_lo, dtype=np.float64)
    e_hi = np.asarray(e_hi, dtype=np.float64)
    c = np.asarray(c, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    return (1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma)


def gaussian_bin_probability_grad(e_lo, e_hi, c, sigma):
    """F-KERN-1/F-KERN-4: value and partial derivatives of the bin integral."""
    e_lo = np.asarray(e_lo, dtype=np.float64)
    e_hi = np.asarray(e_hi, dtype=np.float64)
    c = np.asarray(c, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    return (
        (1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma),
        -1/2*np.sqrt(2)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma),
        (1/2)*np.sqrt(2)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma),
        (1/2)*np.sqrt(2)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma) - 1/2*np.sqrt(2)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma),
        -1/2*np.sqrt(2)*(-c + e_hi)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma**2) + (1/2)*np.sqrt(2)*(-c + e_lo)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma**2),
    )


def taper(offset, sigma, n_sigma):
    """F-KERN-2: smoothstep support taper, 1 on the plateau, 0 beyond n_sigma."""
    offset = np.asarray(offset, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    return -2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**2


def taper_grad(offset, sigma, n_sigma):
    """F-KERN-4: taper value and d/d(offset), d/d(sigma)."""
    offset = np.asarray(offset, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    return (
        -2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**2,
        -(-6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**2 + 6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma)))*np.sign(offset)/sigma,
        (n_sigma/sigma - (n_sigma*sigma - np.abs(offset))/sigma**2)*(-6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))**2 + 6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(offset))/sigma))),
    )


def tapered_bin(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-2: tapered (unnormalized) bin probability."""
    e_lo = np.asarray(e_lo, dtype=np.float64)
    e_hi = np.asarray(e_hi, dtype=np.float64)
    c = np.asarray(c, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    center = np.asarray(center, dtype=np.float64)
    return ((1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma))*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2)


def tapered_bin_grad(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-4: tapered bin and partial derivatives.

    Returns ``(n, dn_de_lo, dn_de_hi, dn_dc, dn_dsigma, dn_dcenter)``. The
    smoothstep clipping contributes a prefactor that vanishes outside the
    transition band; every factor is sympy-generated.
    """
    e_lo = np.asarray(e_lo, dtype=np.float64)
    e_hi = np.asarray(e_hi, dtype=np.float64)
    c = np.asarray(c, dtype=np.float64)
    sigma = np.asarray(sigma, dtype=np.float64)
    center = np.asarray(center, dtype=np.float64)
    return (
        ((1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma))*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2),
        -1/2*np.sqrt(2)*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma),
        (1/2)*np.sqrt(2)*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma),
        ((1/2)*np.sqrt(2)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma) - 1/2*np.sqrt(2)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma))*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2) - ((1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma))*(-6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2 + 6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma)))*np.sign(c - center)/sigma,
        (n_sigma/sigma - (n_sigma*sigma - np.abs(c - center))/sigma**2)*((1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma))*(-6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2 + 6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))) + (-1/2*np.sqrt(2)*(-c + e_hi)*np.exp(-1/2*(-c + e_hi)**2/sigma**2)/(np.sqrt(np.pi)*sigma**2) + (1/2)*np.sqrt(2)*(-c + e_lo)*np.exp(-1/2*(-c + e_lo)**2/sigma**2)/(np.sqrt(np.pi)*sigma**2))*(-2*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**3 + 3*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2),
        ((1/2)*erf((1/2)*np.sqrt(2)*(-c + e_hi)/sigma) - 1/2*erf((1/2)*np.sqrt(2)*(-c + e_lo)/sigma))*(-6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma))**2 + 6*np.minimum(1, np.maximum(0, (n_sigma*sigma - np.abs(c - center))/sigma)))*np.sign(c - center)/sigma,
    )


def normalize(values, denominator):
    """F-KERN-2: column renormalization p = n / D, zero where D <= 0."""
    values = np.asarray(values, dtype=np.float64)
    denominator = np.asarray(denominator, dtype=np.float64)
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(denominator > 0.0, values / denominator, 0.0)


def normalize_grad(values, d_values, denominator, d_denominator):
    """F-KERN-2/F-KERN-4: quotient rule ``-d_denominator*values/denominator**2 + d_values/denominator``."""
    values = np.asarray(values, dtype=np.float64)
    d_values = np.asarray(d_values, dtype=np.float64)
    denominator = np.asarray(denominator, dtype=np.float64)
    d_denominator = np.asarray(d_denominator, dtype=np.float64)
    with np.errstate(divide="ignore", invalid="ignore"):
        probability = np.where(denominator > 0.0, values / denominator, 0.0)
        d_probability = np.where(
            denominator > 0.0,
            -d_denominator*values/denominator**2 + d_values/denominator,
            0.0,
        )
    return probability, d_probability
