"""Generated numeric kernels for ``kc761tool.core`` (D-77).

This package is generated by ``tools/generate_kernels.py`` and committed. On
import, :func:`ensure_fresh` compares the committed manifest with the files on
disk; a stale generator or a hand-edited module triggers an in-place
regeneration when sympy is importable, otherwise a :class:`Kc761toolError` naming
the exact command.
"""

# ruff: noqa: E402, F401

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path

from kc761tool.errors import Kc761toolError

MANIFEST_NAME = "_manifest.json"
GENERATOR_REL = "tools/generate_kernels.py"
_COMMAND = "python tools/generate_kernels.py"
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[2]
_LOADED = False


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def manifest() -> dict:
    """Return the committed manifest."""
    try:
        return json.loads((_HERE / MANIFEST_NAME).read_text(encoding="utf-8"))
    except FileNotFoundError as exc:  # pragma: no cover - corrupted checkout
        raise Kc761toolError(
            f"generated kernel manifest is missing; run '{_COMMAND}'"
        ) from exc


def stale_files() -> list[str]:
    """Return the paths (relative) whose content does not match the manifest."""
    data = manifest()
    stale: list[str] = []
    generator = _REPO_ROOT / GENERATOR_REL
    if not generator.is_file() or _sha256(generator) != data["generator_sha256"]:
        stale.append(GENERATOR_REL)
    for name, digest in data["modules"].items():
        path = _HERE / name
        if not path.is_file() or _sha256(path) != digest:
            stale.append(name)
    return stale


def _regenerate() -> None:
    generator = _REPO_ROOT / GENERATOR_REL
    spec = importlib.util.spec_from_file_location(
        "kc761tool_generate_kernels", generator)
    if spec is None or spec.loader is None:  # pragma: no cover - corrupted checkout
        raise Kc761toolError(f"cannot load the kernel generator: {generator}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.write_all(_REPO_ROOT)


def ensure_fresh() -> None:
    """Regenerate the kernels when the manifest says they are stale."""
    global _LOADED
    if _LOADED:
        return
    stale = stale_files()
    if stale:
        try:
            import sympy  # noqa: F401
        except ImportError as exc:  # pragma: no cover - sympy is a runtime dependency
            raise Kc761toolError(
                "generated kernels are stale ("
                + ", ".join(stale)
                + f"); install sympy or run '{_COMMAND}'"
            ) from exc
        _regenerate()
        remaining = stale_files()
        if remaining:  # pragma: no cover - regeneration is deterministic
            raise Kc761toolError(
                "kernel regeneration did not converge; stale: " +
                ", ".join(remaining)
            )
    _LOADED = True


ensure_fresh()

from kc761tool.core._gen import kernel_expr, model_expr  # noqa: E402
