# GENERATED by tools/generate_kernels.py -- do not edit.
# sympy version: 1.14.0
# formula ids: F-MODEL-1, F-MODEL-2, F-MODEL-3, F-MODEL-4
# command: python tools/generate_kernels.py
# ruff: noqa: E501, F401, I001

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def energy_kev(channel, c0, k1, k2, k3, channel_max):
    """F-MODEL-1: cubic in the internal slope basis (keV)."""
    channel = np.asarray(channel, dtype=np.float64)
    return c0 + (1/3)*channel**3*(2*k1 - 4*k2 + 2*k3)/channel_max**2 + (1/2)*channel**2*(-3*k1 + 4*k2 - k3)/channel_max + channel*k1


def energy_derivative_kev_per_channel(channel, k1, k2, k3, channel_max):
    """F-MODEL-3: dE/dch (keV per channel)."""
    channel = np.asarray(channel, dtype=np.float64)
    return 2*channel**2*k1/channel_max**2 - 4*channel**2*k2/channel_max**2 + 2*channel**2*k3/channel_max**2 - 3*channel*k1/channel_max + 4*channel*k2/channel_max - channel*k3/channel_max + k1


def energy_grad_internal(channel, channel_max):
    """F-MODEL-2: dE/d(c0, k1, k2, k3), shape (4, *channel.shape)."""
    channel = np.asarray(channel, dtype=np.float64)
    return np.stack(np.broadcast_arrays(1, (2/3)*channel**3/channel_max**2 - 3/2*channel**2/channel_max + channel, -4/3*channel**3/channel_max**2 + 2*channel**2/channel_max, (2/3)*channel**3/channel_max**2 - 1/2*channel**2/channel_max), axis=0)


def energy_grad_reported(channel):
    """F-MODEL-2: dE/d(c0, c1, c2, c3), shape (4, *channel.shape)."""
    channel = np.asarray(channel, dtype=np.float64)
    return np.stack(np.broadcast_arrays(1, channel, channel**2, channel**3), axis=0)


def internal_to_reported(c0, k1, k2, k3, channel_max):
    """F-MODEL-2: (c0, k1, k2, k3) -> (c0, c1, c2, c3)."""
    return (c0, k1, (1/2)*(-3*k1 + 4*k2 - k3)/channel_max, (1/3)*(2*k1 - 4*k2 + 2*k3)/channel_max**2)


def reported_to_internal(c0, c1, c2, c3, channel_max):
    """F-MODEL-2: inverse of internal_to_reported."""
    return (c0, c1, c1 + c2*channel_max + (3/4)*c3*channel_max**2, c1 + 2*c2*channel_max + 3*c3*channel_max**2)


def internal_jacobian(channel_max):
    """F-MODEL-2: constant d(reported)/d(internal), shape (4, 4)."""
    return np.array(
        [
            [1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, -(3/2)/channel_max, 2/channel_max, -(1/2)/channel_max],
            [0, (2/3)/channel_max**2, -(4/3) /
             channel_max**2, (2/3)/channel_max**2],
        ],
        dtype=np.float64,
    )


def resolution_variance(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma**2(E) in keV**2, used exactly as written."""
    energy_kev = np.asarray(energy_kev, dtype=np.float64)
    return b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2


def resolution_variance_grad(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: d(sigma**2)/d(b0, b1, b2), shape (3, *energy.shape)."""
    energy_kev = np.asarray(energy_kev, dtype=np.float64)
    return np.stack(np.broadcast_arrays(2*b0*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2, b1*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev, (1/2)*b2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2), axis=0)


def resolution_sigma(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma(E) in keV."""
    energy_kev = np.asarray(energy_kev, dtype=np.float64)
    return np.sqrt(b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2)


def resolution_sigma_grad(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma and d(sigma)/d(b0, b1, b2), shape (3, *energy.shape)."""
    energy_kev = np.asarray(energy_kev, dtype=np.float64)
    return (
        np.sqrt(b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev)) /
                resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2),
        np.stack(np.broadcast_arrays(b0*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2/np.sqrt(b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2), (1/2)*b1*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/(resol_e_ref_kev*np.sqrt(b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)
                 ** 2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2)), (1/4)*b2*(energy_kev + np.abs(energy_kev))**2/(resol_e_ref_kev**2*np.sqrt(b0**2*(1 - 1/2*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev)**2 + (1/2)*b1**2*(2 - (energy_kev + np.abs(energy_kev))/resol_e_ref_kev)*(energy_kev + np.abs(energy_kev))/resol_e_ref_kev + (1/4)*b2**2*(energy_kev + np.abs(energy_kev))**2/resol_e_ref_kev**2))), axis=0),
    )
