#!/usr/bin/env python3
"""Generate ``kc761/core/_gen`` from single-source sympy expressions.

Usage: ``python tools/generate_kernels.py``

The generated modules are committed (D-77). Every value and every derivative
comes from the same symbolic expression; the generator only composes the
primitive derivatives that ``sympy.diff`` produced. ``kc761.core._gen`` checks
the manifest at import time and regenerates in place when the generator or a
generated module changed (sympy is a runtime dependency).

No timestamps or environment-dependent strings are written, so repeated runs
with the same sympy version are byte-identical.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import sympy as sp
from sympy.printing.numpy import NumPyPrinter
from sympy.printing.pycode import pycode

REPO_ROOT = Path(__file__).resolve().parents[1]
GEN_DIR = REPO_ROOT / "kc761" / "core" / "_gen"
GENERATOR_REL = "tools/generate_kernels.py"
MANIFEST_NAME = "_manifest.json"
COMMAND = "python tools/generate_kernels.py"
FORMULA_IDS = (
    "F-MODEL-1",
    "F-MODEL-2",
    "F-MODEL-3",
    "F-MODEL-4",
    "F-KERN-1",
    "F-KERN-2",
    "F-KERN-4",
)

# ---------------------------------------------------------------------------
# code printer


class _NumPyPrinter(NumPyPrinter):
    """NumPy printer with the primitives the kernels need."""

    def _print_erf(self, expr: sp.Expr) -> str:
        return f"erf({self._print(expr.args[0])})"

    def _print_Max(self, expr: sp.Expr) -> str:
        return "numpy.maximum(" + ", ".join(self._print(a) for a in expr.args) + ")"

    def _print_Min(self, expr: sp.Expr) -> str:
        return "numpy.minimum(" + ", ".join(self._print(a) for a in expr.args) + ")"

    def _print_Abs(self, expr: sp.Expr) -> str:
        return f"numpy.abs({self._print(expr.args[0])})"

    def _print_sign(self, expr: sp.Expr) -> str:
        return f"numpy.sign({self._print(expr.args[0])})"


_PRINTER = _NumPyPrinter()


def _print(expr: sp.Expr) -> str:
    return _PRINTER.doprint(expr).replace("numpy.", "np.")


def _scalar_print(expr: sp.Expr) -> str:
    """Render a scalar (``math``/builtin) variant of the same sympy expression.

    This is the numba-compatible rendering of the single source: ``pycode``
    maps ``exp``/``sqrt``/``erf`` to ``math.*`` and ``Min``/``Max``/``Abs``/
    ``sign`` to the Python builtins, which ``numba.njit`` accepts.
    """
    return pycode(expr, standard="python3")

def _arrayify(*names: str) -> str:
    return "".join(f"    {name} = np.asarray({name}, dtype=np.float64)\n" for name in names)


def _header(ids: tuple[str, ...], *, needs_erf: bool, needs_math: bool = False) -> str:
    lines = [
        "# GENERATED by tools/generate_kernels.py -- do not edit.",
        f"# sympy version: {sp.__version__}",
        f"# formula ids: {', '.join(ids)}",
        f"# command: {COMMAND}",
        "# ruff: noqa: E501, F401, I001",
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_math:
        lines += ["import math", ""]
    lines += [
        "import numpy as np",
        "from numpy.typing import NDArray",
    ]
    if needs_erf:
        lines.append("from scipy.special import erf")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# symbols

CH = sp.Symbol("channel", real=True)
CH_MAX = sp.Symbol("channel_max", positive=True)
C0, K1, K2, K3 = sp.symbols("c0 k1 k2 k3", real=True)
RC0, RC1, RC2, RC3 = sp.symbols("c0 c1 c2 c3", real=True)
E_ARG = sp.Symbol("energy_kev", real=True)
B0, B1, B2 = sp.symbols("b0 b1 b2", real=True)
E_REF = sp.Symbol("resol_e_ref_kev", positive=True)
E_LO, E_HI, C_SRC, SIGMA = sp.symbols("e_lo e_hi c sigma", positive=True)
N_SIGMA = sp.Symbol("n_sigma", positive=True)
OFFSET = sp.Symbol("offset", real=True)
CENTER = sp.Symbol("center", real=True)
S_RAW = sp.Symbol("s_raw", real=True)
W_SC = sp.Symbol("w_sc", real=True)
T_PARAM = sp.Symbol("t_param", real=True)


def _s_raw(offset_expression: sp.Expr) -> sp.Expr:
    return (N_SIGMA * SIGMA - sp.Abs(offset_expression)) / SIGMA


def _clip_smoothstep(offset_expression: sp.Expr) -> sp.Expr:
    """Clipped smoothstep coordinate, 0 beyond ``n_sigma``, 1 on the plateau."""
    return sp.Min(1, sp.Max(0, _s_raw(offset_expression)))


def _taper_expression(offset_expression: sp.Expr) -> sp.Expr:
    w_expr = 3 * W_SC**2 - 2 * W_SC**3
    return w_expr.subs(W_SC, _clip_smoothstep(offset_expression))


def _taper_derivative(offset_expression: sp.Expr, variable: sp.Symbol) -> sp.Expr:
    """Chain rule with the clipping prefactor.

    ``sympy.diff`` of the clipped expression would produce ``Piecewise``
    branches; the prefactor ``6 s - 6 s**2`` vanishes exactly where the clip
    saturates, so evaluating the unclipped chain rule at the clipped
    coordinate is the correct extension and keeps a single symbolic source.
    """
    w_expr = 3 * W_SC**2 - 2 * W_SC**3
    dw_ds = sp.diff(w_expr, W_SC)
    ds_dvariable = sp.diff(_s_raw(offset_expression), variable)
    return (dw_ds * ds_dvariable).subs(W_SC, _clip_smoothstep(offset_expression))


# ---------------------------------------------------------------------------
# energy model F-MODEL-1/F-MODEL-2/F-MODEL-3


def _energy_expressions() -> dict[str, Any]:
    a2 = (4 * K2 - 3 * K1 - K3) / (2 * CH_MAX)
    a3 = 2 * (K1 - 2 * K2 + K3) / (3 * CH_MAX**2)
    energy = C0 + K1 * CH + a2 * CH**2 + a3 * CH**3

    reported = sp.Matrix([C0, K1, a2, a3])
    internal = sp.Matrix([C0, K1, K2, K3])

    energy_reported = RC0 + RC1 * CH + RC2 * CH**2 + RC3 * CH**3

    k1_from_reported = RC1
    k2_from_reported = RC1 + CH_MAX * RC2 + sp.Rational(3, 4) * CH_MAX**2 * RC3
    k3_from_reported = RC1 + 2 * CH_MAX * RC2 + 3 * CH_MAX**2 * RC3

    t_axis = (E_ARG + sp.Abs(E_ARG)) / (2 * E_REF)
    variance = (
        (1 - t_axis) ** 2 * B0**2 + 2 * (1 - t_axis) * t_axis * B1**2 + t_axis**2 * B2**2
    )
    sigma = sp.sqrt(variance)

    return {
        "energy": energy,
        "energy_derivative": sp.expand(sp.diff(energy, CH)),
        "gradients": [sp.expand(sp.diff(energy, q)) for q in (C0, K1, K2, K3)],
        "reported": tuple(reported),
        "jacobian": reported.jacobian(internal),
        "reported_gradients": [
            sp.expand(sp.diff(energy_reported, q)) for q in (RC0, RC1, RC2, RC3)
        ],
        "inverse": (RC0, k1_from_reported, k2_from_reported, k3_from_reported),
        "variance": variance,
        "variance_gradients": [sp.diff(variance, b) for b in (B0, B1, B2)],
        "sigma": sigma,
        "sigma_gradients": [sp.diff(sigma, b) for b in (B0, B1, B2)],
    }


def _model_module() -> str:
    e = _energy_expressions()
    gradients = ", ".join(_print(g) for g in e["gradients"])
    reported_gradients = ", ".join(_print(g) for g in e["reported_gradients"])
    reported = ", ".join(_print(v) for v in e["reported"])
    inverse = ", ".join(_print(v) for v in e["inverse"])
    jacobian_rows = ",\n            ".join(
        "[" + ", ".join(_print(e["jacobian"][i, j]) for j in range(4)) + "]"
        for i in range(4)
    )
    variance_gradients = ", ".join(_print(g) for g in e["variance_gradients"])
    sigma_gradients = ", ".join(_print(g) for g in e["sigma_gradients"])

    return (
        _header(("F-MODEL-1", "F-MODEL-2", "F-MODEL-3", "F-MODEL-4"), needs_erf=False)
        + f'''

def energy_kev(channel, c0, k1, k2, k3, channel_max):
    """F-MODEL-1: cubic in the internal slope basis (keV)."""
{_arrayify("channel")}    return {_print(e["energy"])}


def energy_derivative_kev_per_channel(channel, k1, k2, k3, channel_max):
    """F-MODEL-3: dE/dch (keV per channel)."""
{_arrayify("channel")}    return {_print(e["energy_derivative"])}


def energy_grad_internal(channel, channel_max):
    """F-MODEL-2: dE/d(c0, k1, k2, k3), shape (4, *channel.shape)."""
{_arrayify("channel")}    return np.stack(np.broadcast_arrays({gradients}), axis=0)


def energy_grad_reported(channel):
    """F-MODEL-2: dE/d(c0, c1, c2, c3), shape (4, *channel.shape)."""
{_arrayify("channel")}    return np.stack(np.broadcast_arrays({reported_gradients}), axis=0)


def internal_to_reported(c0, k1, k2, k3, channel_max):
    """F-MODEL-2: (c0, k1, k2, k3) -> (c0, c1, c2, c3)."""
    return ({reported})


def reported_to_internal(c0, c1, c2, c3, channel_max):
    """F-MODEL-2: inverse of internal_to_reported."""
    return ({inverse})


def internal_jacobian(channel_max):
    """F-MODEL-2: constant d(reported)/d(internal), shape (4, 4)."""
    return np.array(
        [
            {jacobian_rows},
        ],
        dtype=np.float64,
    )


def resolution_variance(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma**2(E) in keV**2, used exactly as written."""
{_arrayify("energy_kev")}    return {_print(e["variance"])}


def resolution_variance_grad(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: d(sigma**2)/d(b0, b1, b2), shape (3, *energy.shape)."""
{_arrayify("energy_kev")}    return np.stack(np.broadcast_arrays({variance_gradients}), axis=0)


def resolution_sigma(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma(E) in keV."""
{_arrayify("energy_kev")}    return {_print(e["sigma"])}


def resolution_sigma_grad(energy_kev, b0, b1, b2, resol_e_ref_kev):
    """F-MODEL-4: sigma and d(sigma)/d(b0, b1, b2), shape (3, *energy.shape)."""
{_arrayify("energy_kev")}    return (
        {_print(e["sigma"])},
        np.stack(np.broadcast_arrays({sigma_gradients}), axis=0),
    )
'''
    )


# ---------------------------------------------------------------------------
# response kernel F-KERN-1/F-KERN-2/F-KERN-4


def _phi(z: sp.Expr) -> sp.Expr:
    return (1 + sp.erf(z / sp.sqrt(2))) / 2


def _kernel_expressions() -> dict[str, Any]:
    z_hi = (E_HI - C_SRC) / SIGMA
    z_lo = (E_LO - C_SRC) / SIGMA
    probability = _phi(z_hi) - _phi(z_lo)
    probability_gradients = {
        "e_lo": sp.diff(probability, E_LO),
        "e_hi": sp.diff(probability, E_HI),
        "c": sp.diff(probability, C_SRC),
        "sigma": sp.diff(probability, SIGMA),
    }

    offset_expression = CENTER - C_SRC
    taper_centered = _taper_expression(offset_expression)
    unclipped_dc = (3 * W_SC**2 - 2 * W_SC**3)
    dw_ds = sp.diff(unclipped_dc, W_SC)
    dw_dc_centered = (dw_ds * sp.diff(_s_raw(offset_expression), C_SRC)).subs(
        W_SC, _clip_smoothstep(offset_expression)
    )
    dw_dsigma_centered = (dw_ds * sp.diff(_s_raw(offset_expression), SIGMA)).subs(
        W_SC, _clip_smoothstep(offset_expression)
    )

    tapered_bin = probability * taper_centered
    tapered_bin_gradients = {
        "e_lo": probability_gradients["e_lo"] * taper_centered,
        "e_hi": probability_gradients["e_hi"] * taper_centered,
        "c": probability_gradients["c"] * taper_centered + probability * dw_dc_centered,
        "sigma": probability_gradients["sigma"] * taper_centered
        + probability * dw_dsigma_centered,
    }
    dw_dcenter_centered = (
        dw_ds * sp.diff(_s_raw(offset_expression), CENTER)
    ).subs(W_SC, _clip_smoothstep(offset_expression))
    tapered_bin_gradients["center"] = probability * dw_dcenter_centered

    n_fun = sp.Function("numerator")(T_PARAM)
    d_fun = sp.Function("denominator")(T_PARAM)
    quotient = sp.diff(n_fun / d_fun, T_PARAM)
    quotient = quotient.subs(sp.Derivative(n_fun, T_PARAM), sp.Symbol("d_numerator"))
    quotient = quotient.subs(sp.Derivative(d_fun, T_PARAM), sp.Symbol("d_denominator"))
    quotient = quotient.subs(n_fun, sp.Symbol("numerator")).subs(d_fun, sp.Symbol("denominator"))
    quotient_source = _print(quotient).replace("d_numerator", "d_values").replace(
        "numerator", "values"
    )
    quotient_expr = quotient.subs(
        {
            sp.Symbol("numerator"): sp.Symbol("values"),
            sp.Symbol("d_numerator"): sp.Symbol("d_values"),
        }
    )

    return {
        "probability": probability,
        "probability_gradients": probability_gradients,
        "taper": _taper_expression(OFFSET),
        "taper_dx": _taper_derivative(OFFSET, OFFSET),
        "taper_dsigma": _taper_derivative(OFFSET, SIGMA),
        "tapered_bin": tapered_bin,
        "tapered_bin_gradients": tapered_bin_gradients,
        "quotient_source": quotient_source,
        "quotient_expr": quotient_expr,
    }


def _cse_lines(expressions: list[sp.Expr]) -> tuple[str, list[str]]:
    """Render sympy common-subexpression assignments plus the reduced returns.

    The generated kernel expressions share the taper and Gaussian factors many
    times; emitting them once through ``sympy.cse`` keeps the same formula (the
    generator is still the single source) while removing the repeated NumPy
    evaluations that dominated the response Jacobian (D-172).
    """
    replacements, reduced = sp.cse(expressions, optimizations="basic")
    body = "".join(f"    {symbol} = {_print(expr)}\n" for symbol, expr in replacements)
    return body, [_print(expr) for expr in reduced]


def _return_single(expressions: list[sp.Expr]) -> str:
    body, reduced = _cse_lines(expressions)
    return f"{body}    return {reduced[0]}\n"


def _return_tuple(expressions: list[sp.Expr]) -> str:
    body, reduced = _cse_lines(expressions)
    entries = "".join(f"        {expr},\n" for expr in reduced)
    return f"{body}    return (\n{entries}    )\n"


def _scalar_cse_lines(expressions: list[sp.Expr]) -> tuple[str, list[str]]:
    """Scalar (numba-compatible) counterpart of :func:`_cse_lines`."""
    replacements, reduced = sp.cse(expressions, optimizations="basic")
    body = "".join(f"    {symbol} = {_scalar_print(expr)}\n" for symbol, expr in replacements)
    return body, [_scalar_print(expr) for expr in reduced]


def _scalar_return_single(expressions: list[sp.Expr]) -> str:
    body, reduced = _scalar_cse_lines(expressions)
    return f"{body}    return {reduced[0]}\n"


def _scalar_return_tuple(expressions: list[sp.Expr]) -> str:
    body, reduced = _scalar_cse_lines(expressions)
    entries = "".join(f"        {expr},\n" for expr in reduced)
    return f"{body}    return (\n{entries}    )\n"


def _kernel_module() -> str:
    e = _kernel_expressions()
    n_grad = e["tapered_bin_gradients"]
    kernel_returns = [
        e["tapered_bin"],
        n_grad["e_lo"],
        n_grad["e_hi"],
        n_grad["c"],
        n_grad["sigma"],
        n_grad["center"],
    ]
    quotient_return = _return_single([e["quotient_expr"]])
    quotient_scalar_return = _scalar_return_single([e["quotient_expr"]])

    return (
        _header(("F-KERN-1", "F-KERN-2", "F-KERN-4"), needs_erf=True, needs_math=True)
        + f'''

import numba


def _jit(function):
    """Compile a scalar kernel with numba (cache=True; numba is a hard dep, D-174)."""
    return numba.njit(cache=True)(function)


def gaussian_bin_probability(e_lo, e_hi, c, sigma):
    """F-KERN-1: exact Gaussian bin integral (no taper)."""
{_arrayify("e_lo", "e_hi", "c", "sigma")}{_return_single([e["probability"]])}


def taper(offset, sigma, n_sigma):
    """F-KERN-2: smoothstep support taper, 1 on the plateau, 0 beyond n_sigma."""
{_arrayify("offset", "sigma")}{_return_single([e["taper"]])}


def taper_grad(offset, sigma, n_sigma):
    """F-KERN-4: taper value and d/d(offset), d/d(sigma)."""
{_arrayify("offset", "sigma")}{_return_tuple([e["taper"], e["taper_dx"], e["taper_dsigma"]])}


def tapered_bin(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-2: tapered (unnormalized) bin probability."""
{_arrayify("e_lo", "e_hi", "c", "sigma", "center")}{_return_single([e["tapered_bin"]])}


def tapered_bin_grad(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-4: tapered bin and partial derivatives.

    Returns ``(n, dn_de_lo, dn_de_hi, dn_dc, dn_dsigma, dn_dcenter)``. The
    smoothstep clipping contributes a prefactor that vanishes outside the
    transition band; every factor is sympy-generated.
    """
{_arrayify("e_lo", "e_hi", "c", "sigma", "center")}{_return_tuple(kernel_returns)}


@_jit
def scalar_tapered_bin(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-2 scalar rendering of the same sympy expression (D-174)."""
{_scalar_return_single([e["tapered_bin"]])}

@_jit
def scalar_tapered_bin_grad(e_lo, e_hi, c, sigma, center, n_sigma):
    """F-KERN-4 scalar rendering of the same sympy expression (D-174)."""
{_scalar_return_tuple(kernel_returns)}

@_jit
def scalar_normalize_derivative(values, d_values, denominator, d_denominator):
    """F-KERN-2/F-KERN-4 scalar derivative rendering of the same sympy expression."""
{quotient_scalar_return}


def normalize(values, denominator):
    """F-KERN-2: column renormalization p = n / D, zero where D <= 0."""
    values = np.asarray(values, dtype=np.float64)
    denominator = np.asarray(denominator, dtype=np.float64)
    with np.errstate(divide="ignore", invalid="ignore"):
        return np.where(denominator > 0.0, values / denominator, 0.0)


def normalize_derivative(values, d_values, denominator, d_denominator):
    """F-KERN-2/F-KERN-4: renormalized derivative ``{e["quotient_source"]}``."""
{_arrayify("values", "d_values", "denominator", "d_denominator")}{quotient_return}
'''
    )


# ---------------------------------------------------------------------------
# static package init


_INIT_TEMPLATE = '''"""Generated numeric kernels for ``kc761.core`` (D-77).

This package is generated by ``tools/generate_kernels.py`` and committed. On
import, :func:`ensure_fresh` compares the committed manifest with the files on
disk; a stale generator or a hand-edited module triggers an in-place
regeneration when sympy is importable, otherwise a :class:`Kc761Error` naming
the exact command.
"""

# ruff: noqa: E402, F401

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path

from kc761.errors import Kc761Error

MANIFEST_NAME = "_manifest.json"
GENERATOR_REL = "tools/generate_kernels.py"
_COMMAND = "python tools/generate_kernels.py"
_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[2]
_LOADED = False


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def manifest() -> dict:
    """Return the committed manifest."""
    try:
        return json.loads((_HERE / MANIFEST_NAME).read_text(encoding="utf-8"))
    except FileNotFoundError as exc:  # pragma: no cover - corrupted checkout
        raise Kc761Error(
            f"generated kernel manifest is missing; run '{_COMMAND}'"
        ) from exc


def stale_files() -> list[str]:
    """Return the paths (relative) whose content does not match the manifest."""
    data = manifest()
    stale: list[str] = []
    generator = _REPO_ROOT / GENERATOR_REL
    if not generator.is_file() or _sha256(generator) != data["generator_sha256"]:
        stale.append(GENERATOR_REL)
    for name, digest in data["modules"].items():
        path = _HERE / name
        if not path.is_file() or _sha256(path) != digest:
            stale.append(name)
    return stale


def _regenerate() -> None:
    generator = _REPO_ROOT / GENERATOR_REL
    spec = importlib.util.spec_from_file_location("kc761_generate_kernels", generator)
    if spec is None or spec.loader is None:  # pragma: no cover - corrupted checkout
        raise Kc761Error(f"cannot load the kernel generator: {generator}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.write_all(_REPO_ROOT)


def ensure_fresh() -> None:
    """Regenerate the kernels when the manifest says they are stale."""
    global _LOADED
    if _LOADED:
        return
    stale = stale_files()
    if stale:
        try:
            import sympy  # noqa: F401
        except ImportError as exc:  # pragma: no cover - sympy is a runtime dependency
            raise Kc761Error(
                "generated kernels are stale ("
                + ", ".join(stale)
                + f"); install sympy or run '{_COMMAND}'"
            ) from exc
        _regenerate()
        remaining = stale_files()
        if remaining:  # pragma: no cover - regeneration is deterministic
            raise Kc761Error(
                "kernel regeneration did not converge; stale: " + ", ".join(remaining)
            )
    _LOADED = True


ensure_fresh()

from kc761.core._gen import kernel_expr, model_expr  # noqa: E402
'''


# ---------------------------------------------------------------------------
# output


def _render_modules() -> dict[str, str]:
    return {
        "__init__.py": _INIT_TEMPLATE,
        "model_expr.py": _model_module(),
        "kernel_expr.py": _kernel_module(),
    }


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    temp.write_text(text, encoding="utf-8", newline="\n")
    temp.replace(path)


def write_all(root: Path = REPO_ROOT) -> None:
    """Write the generated package and its manifest below ``root``."""
    gen_dir = root / "kc761" / "core" / "_gen"
    modules = _render_modules()
    for name, text in modules.items():
        _write_text(gen_dir / name, text)

    generator = root / GENERATOR_REL
    manifest = {
        "command": COMMAND,
        "formula_ids": list(FORMULA_IDS),
        "generator_sha256": hashlib.sha256(generator.read_bytes()).hexdigest(),
        "modules": {
            name: hashlib.sha256((gen_dir / name).read_bytes()).hexdigest()
            for name in sorted(modules)
        },
        "sympy_version": sp.__version__,
    }
    _write_text(gen_dir / MANIFEST_NAME, json.dumps(manifest, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    write_all()
    print(f"wrote generated kernels to {GEN_DIR}")
